apiVersion:  v1
kind: Pod
metadata:
  name: frontend
  labels:
    component: web
spec:
  containers:
   - name: frontend
     image: ademola123/testing-frontend:v2
     ports:
      - containerPort: 3000